//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itau.CoinExchange.WebClients {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebClientsMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebClientsMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Itau.CoinExchange.WebClients.WebClientsMessages", typeof(WebClientsMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível realizar a conversão solicitada..
        /// </summary>
        internal static string CurrconvApiClient_Convertion_Is_Not_Possible {
            get {
                return ResourceManager.GetString("CurrconvApiClient_Convertion_Is_Not_Possible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O serviço de conversão de moedas está operando normalmente..
        /// </summary>
        internal static string CurrconvApiHealthCheck_Healthy {
            get {
                return ResourceManager.GetString("CurrconvApiHealthCheck_Healthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O serviço de conversão de moedas está inoperante..
        /// </summary>
        internal static string CurrconvApiHealthCheck_UnHealthy {
            get {
                return ResourceManager.GetString("CurrconvApiHealthCheck_UnHealthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível realizar a conversão solicitada. {0}.
        /// </summary>
        internal static string ExchangeRateApiClient_Convert_Is_Not_Possible {
            get {
                return ResourceManager.GetString("ExchangeRateApiClient_Convert_Is_Not_Possible", resourceCulture);
            }
        }
    }
}
