name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-rc.2.20479.15
    - name: Install dependencies
      run: dotnet restore CotacaoDeMoedas.sln
      
    - name: Build
      run: dotnet build CotacaoDeMoedas.sln --configuration Release --no-restore
      
    - name: Test
      run: dotnet test CotacaoDeMoedas.sln --no-restore --verbosity normal
